### ISSUE TITLE
Adding Git and Github

### ISSUE THREAD

**Issue by Pratham-Mishra178** [Jassi10000/LGM-SOC-21#6]
I want to add the git and github beginners resource to the community

**Comment by Pratham-Mishra178** [comment]
Here I want to add the Git and Github resource

**Comment by Jassi10000-zz** [comment]
@Pratham-Mishra178 Buddy where's the description , how can I know what you want to do 
Please respect Open Source and properly state what step you want to take regarding project ?

**Comment by Pratham-Mishra178** [comment]
Sorry for that

**Comment by Jassi10000-zz** [comment]
Sure @Pratham-Mishra178 , you can go forward with your contributions
