### ISSUE TITLE
Adding Docker

### ISSUE THREAD

**Issue by Samikmalhotra** [Jassi10000/LGM-SOC-21#7]
Greetings sir, I believe the knowledge of docker and containers would also be helpful in the projects for open source. 
I found this docker tutorial helpful: [Docker](https://www.youtube.com/watch?v=fqMOX6JJhGo)
I am currently a beginner at open source and thus request you to correct me if I did something wrong.
I also request you to enlighten me how can I apply for LGM-SOC-21 and how I can improve my open source contributuions.
Thank you

**Comment by Jassi10000-zz** [comment]
@Samikmalhotra Rightly said , Docker and Containers are really an essential skills that we can learn . Thanks for providing a link to the resource . I will give you one more , you can add that as well 
https://youtu.be/pTFZFxd4hOI

No issues, you can learn in LGM-SOC'21 ,
You can simply get started with projects on https://letsgrowmore.in/projects/ 
Choose any one  project according to your tech stack  
You can refer to my  live session on how to fork and clone a project and start contributing on Let's Grow more youtube channel

Just take small steps , do small contributions , understand the process and you will be good to do

Now if you want to contribute after watching the video , just add Docker to repo , I will assign you

**Comment by Samikmalhotra** [comment]
Thank you for the guidance sir, I have submitted the pull request to add resources for docker. LGM seems like a great community and I'll be honoured to contribute in the organisation, however I am a little preoccupied with my End Semester Exams and will start contributing as soon as I am done with them.
Again sir, Thank You.
